from __future__ import annotations

from app.schemas import PromptTemplate


PROMPT_TEMPLATES: list[PromptTemplate] = [
    PromptTemplate(
        id="kitchen-refurb",
        title="Kitchen refurbishment",
        description="Strip out, new units (client supply), tiling, electrics, plumbing, flooring, decorating.",
        category="Interiors",
        prompt=(
            "PROPERTY:\n"
            "Type: Flat\n"
            "Location: London\n"
            "Ceiling height: 2.4m\n"
            "Property occupied during works\n"
            "\n"
            "FULL SCOPE:\n"
            "Kitchen refurbishment\n"
            "\n"
            "FLOOR AREAS & ROOMS:\n"
            "Ground Floor\n"
            "  Kitchen/Diner: 4.5 x 3.2\n"
            "\n"
            "DEMOLITION:\n"
            "Strip out existing kitchen units, worktops, and appliances\n"
            "Remove wall tiles to splashback area (2.4 x 0.6m)\n"
            "Remove vinyl floor finish to kitchen\n"
            "\n"
            "PLASTERING:\n"
            "Patch skim to kitchen walls where disturbed: approx 6m2\n"
            "\n"
            "JOINERY:\n"
            "New kitchen units and worktops — client supply, contractor fit (1.5 days carpenter)\n"
            "\n"
            "TILING:\n"
            "Wall tiling to splashback: 2.4 x 0.6m\n"
            "\n"
            "PLUMBING:\n"
            "Reconnect sink (1 no.)\n"
            "Reconnect dishwasher (1 no.)\n"
            "\n"
            "ELECTRICAL:\n"
            "Kitchen: 8 downlights\n"
            "Kitchen: 6 double sockets\n"
            "Kitchen: 1 cooker circuit hardwire\n"
            "Kitchen: 1 appliance spur for dishwasher\n"
            "\n"
            "DECORATING:\n"
            "Mist coat and 2 coats emulsion to kitchen walls\n"
            "Mist coat and 2 coats emulsion to kitchen ceiling\n"
            "\n"
            "WOODWORK PAINTING:\n"
            "Gloss to skirting boards: 12 lm\n"
            "Gloss to 1 internal door (both sides) and architrave\n"
            "\n"
            "FLOORING:\n"
            "Engineered timber to kitchen/diner: 14.4m2\n"
        ),
    ),
    PromptTemplate(
        id="bathroom-renovation",
        title="Bathroom renovation",
        description="Full strip out, new sanitaryware (client supply), wall and floor tiling, electrics, plumbing.",
        category="Interiors",
        prompt=(
            "PROPERTY:\n"
            "Type: Terraced house\n"
            "Location: London\n"
            "Ceiling height: 2.4m\n"
            "Property occupied during works\n"
            "\n"
            "FULL SCOPE:\n"
            "Bathroom renovation\n"
            "\n"
            "FLOOR AREAS & ROOMS:\n"
            "First Floor\n"
            "  Bathroom: 2.5 x 2.0\n"
            "\n"
            "DEMOLITION:\n"
            "Strip out existing bath, WC, basin, and shower enclosure\n"
            "Hack off existing wall and floor tiles\n"
            "Remove stud partition if present\n"
            "\n"
            "PLASTERING:\n"
            "Patch plaster to walls where required after strip out: approx 4m2\n"
            "\n"
            "TILING:\n"
            "Full-height wall tiling to bathroom (all four walls, 2.4m height): approx 22m2\n"
            "Floor tiling to bathroom: 5.0m2\n"
            "\n"
            "PLUMBING:\n"
            "Install WC (client supply sanitaryware)\n"
            "Install basin with pedestal (client supply sanitaryware)\n"
            "Install bath (client supply sanitaryware)\n"
            "Install shower enclosure with thermostatic valve (client supply)\n"
            "Install heated towel rail (1 no.)\n"
            "All pipework alterations and connections\n"
            "\n"
            "ELECTRICAL:\n"
            "Bathroom: 2 downlights (IP65)\n"
            "Bathroom: 1 extractor fan with ducting to external\n"
            "Bathroom: 1 shaver socket (IP rated)\n"
            "\n"
            "DECORATING:\n"
            "Mist coat and 2 coats moisture-resistant emulsion to bathroom ceiling\n"
            "\n"
            "WOODWORK PAINTING:\n"
            "Gloss to skirting: 9 lm\n"
            "Gloss to 1 internal door (both sides) and architrave\n"
        ),
    ),
    PromptTemplate(
        id="full-house-refurb-victorian",
        title="Full house refurbishment — Victorian terrace",
        description="3-bed Victorian terrace: demolition, structural, kitchen, bathroom, flooring, electrics, decorating.",
        category="Whole property",
        prompt=(
            "PROPERTY:\n"
            "Type: Terraced house\n"
            "Location: North London\n"
            "Storeys: 2\n"
            "Ceiling height: 2.75m ground floor, 2.55m first floor\n"
            "Property empty during works\n"
            "Finish level: high\n"
            "\n"
            "FULL SCOPE:\n"
            "Full house refurbishment\n"
            "\n"
            "FLOOR AREAS & ROOMS:\n"
            "Ground Floor\n"
            "  Kitchen/Diner: 5.2 x 4.8\n"
            "  Living Room: 4.5 x 3.9\n"
            "  Hallway: 1.2 x 6.0\n"
            "\n"
            "First Floor\n"
            "  Master Bedroom: 4.2 x 3.8\n"
            "  Bedroom 2: 3.5 x 3.2\n"
            "  Bedroom 3: 2.8 x 2.6\n"
            "  Bathroom: 2.2 x 1.9\n"
            "\n"
            "DEMOLITION:\n"
            "Strip out existing kitchen units and appliances\n"
            "Strip out bathroom suite (bath, WC, basin, shower enclosure)\n"
            "Remove all floor coverings throughout\n"
            "Remove non-structural partition wall between kitchen and dining room\n"
            "\n"
            "STEELWORKS:\n"
            "New RSJ beam 203x203 UC @52 with padstones, kitchen opening approx 3.2m span — specialist subcontract, price as PC sum £3,500\n"
            "\n"
            "PLASTERING:\n"
            "Full skim to kitchen/diner walls and ceiling after structural works: 62m2\n"
            "Patch skim to living room and hallway walls where disturbed: approx 12m2\n"
            "\n"
            "JOINERY:\n"
            "New kitchen units and worktops — client supply, contractor fit (2 days carpenter)\n"
            "\n"
            "TILING:\n"
            "Kitchen splashback wall tiling: 2.4 x 0.6m\n"
            "Bathroom full-height wall tiling (all four walls, 2.4m height): approx 20m2\n"
            "Bathroom floor tiling: 4.2m2\n"
            "\n"
            "PLUMBING:\n"
            "New sink and dishwasher connection in kitchen (2 no. connections)\n"
            "Install bath (client supply sanitaryware)\n"
            "Install WC (client supply sanitaryware)\n"
            "Install basin (client supply sanitaryware)\n"
            "Install shower enclosure with thermostatic valve (client supply)\n"
            "Install heated towel rail (1 no.)\n"
            "All plumbing alterations and connections\n"
            "\n"
            "ELECTRICAL:\n"
            "Rewire ground floor — new sockets and lighting circuits\n"
            "Kitchen: 10 downlights\n"
            "Living Room: 6 downlights\n"
            "Replace all switches and sockets throughout house: 24 outlets\n"
            "New consumer unit spur for kitchen appliances\n"
            "Bathroom: 2 downlights (IP65), 1 extractor fan\n"
            "\n"
            "DECORATING:\n"
            "Mist coat and 2 coats emulsion to all rooms — walls and ceilings throughout\n"
            "\n"
            "WOODWORK PAINTING:\n"
            "Gloss to all skirting boards throughout: 56 lm\n"
            "Gloss to 8 internal doors (both sides) and architraves\n"
            "\n"
            "FLOORING:\n"
            "Engineered oak to ground floor throughout: 54m2\n"
            "Carpet to Master Bedroom: 16m2\n"
            "Carpet to Bedroom 2: 11.2m2\n"
            "Carpet to Bedroom 3: 7.3m2\n"
            "\n"
            "STRUCTURE:\n"
            "Repoint front brick facade: 28m2\n"
            "New timber fence panels to rear boundary: 18 lm\n"
        ),
    ),
    PromptTemplate(
        id="loft-conversion",
        title="Loft conversion — rear dormer",
        description="Rear dormer structural works, new bedroom and ensuite, insulation, MEP, plastering, finishes.",
        category="Extensions",
        prompt=(
            "PROPERTY:\n"
            "Type: Terraced house\n"
            "Location: London\n"
            "Ceiling height: 2.4m (loft ridge)\n"
            "Property occupied during works\n"
            "\n"
            "FULL SCOPE:\n"
            "Loft conversion with rear dormer\n"
            "\n"
            "FLOOR AREAS & ROOMS:\n"
            "Loft\n"
            "  Loft Bedroom: 6.0 x 4.5\n"
            "  Loft Ensuite: 2.5 x 1.8\n"
            "\n"
            "STRUCTURE:\n"
            "Rear dormer structure: 4.5 x 3.5m\n"
            "New steel beam for loft structural opening — specialist subcontract, PC sum £2,800\n"
            "New floor joists and boarding\n"
            "Flat roof to dormer: 15.75m2\n"
            "\n"
            "WINDOWS:\n"
            "2 no. Velux MK04 to front slope\n"
            "Dormer window (aluminium, fixed and opening) — 1 no.\n"
            "\n"
            "CEILINGS & INSULATION:\n"
            "120mm insulation between rafters throughout loft\n"
            "50mm insulated plasterboard under rafters\n"
            "New plasterboard ceiling to dormer flat soffit: 15.75m2\n"
            "\n"
            "CARPENTRY:\n"
            "Stud partition to divide loft bedroom and ensuite\n"
            "New loft staircase — contractor supply and fit\n"
            "\n"
            "DOORS:\n"
            "2 no. new internal doors (loft bedroom and ensuite) — contractor supply and fit\n"
            "\n"
            "PLASTERING:\n"
            "Skim walls and ceilings to loft bedroom: 72m2\n"
            "Skim walls and ceilings to ensuite: 24m2\n"
            "\n"
            "TILING:\n"
            "Full-height wall tiling to ensuite (all walls, 2.4m): approx 18m2\n"
            "Floor tiling to ensuite: 4.5m2\n"
            "\n"
            "PLUMBING:\n"
            "Install basin in ensuite (contractor supply)\n"
            "Install WC in ensuite (contractor supply)\n"
            "Install shower enclosure in ensuite (contractor supply)\n"
            "Extend soil stack and all pipework\n"
            "Install heated towel rail (1 no.)\n"
            "\n"
            "ELECTRICAL:\n"
            "Loft Bedroom: 6 downlights\n"
            "Loft Bedroom: 4 double sockets\n"
            "Loft Bedroom: 1 TV point\n"
            "Loft Ensuite: 2 downlights (IP65)\n"
            "Loft Ensuite: 1 extractor fan with ducting to external\n"
            "New circuit from consumer unit to loft\n"
            "\n"
            "DECORATING:\n"
            "Mist coat and 2 coats emulsion to loft bedroom walls and ceiling\n"
            "Mist coat moisture-resistant emulsion to ensuite ceiling\n"
            "\n"
            "WOODWORK PAINTING:\n"
            "Gloss to skirting boards loft: 22 lm\n"
            "Gloss to 2 internal doors (both sides) and architraves\n"
            "\n"
            "FLOORING:\n"
            "Carpet to loft bedroom: 27m2\n"
        ),
    ),
    PromptTemplate(
        id="full-flat-decoration",
        title="Full flat redecoration",
        description="Patch plaster, full emulsion throughout, gloss woodwork, new flooring — no structural works.",
        category="Decorating",
        prompt=(
            "PROPERTY:\n"
            "Type: Flat\n"
            "Location: London\n"
            "Ceiling height: 2.4m\n"
            "Property empty during works\n"
            "\n"
            "FULL SCOPE:\n"
            "Full flat redecoration\n"
            "\n"
            "FLOOR AREAS & ROOMS:\n"
            "Ground Floor\n"
            "  Living Room: 5.5 x 4.0\n"
            "  Kitchen: 3.8 x 2.8\n"
            "  Bedroom 1: 4.0 x 3.5\n"
            "  Bedroom 2: 3.2 x 2.8\n"
            "  Bathroom: 2.2 x 1.8\n"
            "  Hallway: 4.5 x 1.2\n"
            "\n"
            "PLASTERING:\n"
            "Patch and make good walls and ceilings throughout: approx 18m2\n"
            "\n"
            "DECORATING:\n"
            "Mist coat and 2 coats emulsion to all walls throughout\n"
            "Mist coat and 2 coats emulsion to all ceilings throughout\n"
            "Moisture-resistant emulsion to bathroom walls and ceiling\n"
            "\n"
            "WOODWORK PAINTING:\n"
            "Gloss to all skirting boards throughout: 38 lm\n"
            "Gloss to 5 internal doors (both sides) and architraves\n"
            "Gloss to window boards: 5 no.\n"
            "\n"
            "ELECTRICAL:\n"
            "Replace 8 light fittings throughout\n"
            "\n"
            "FLOORING:\n"
            "Engineered timber to living room: 22m2\n"
            "Engineered timber to kitchen: 10.6m2\n"
            "Engineered timber to hallway: 5.4m2\n"
            "Carpet to bedroom 1: 14m2\n"
            "Carpet to bedroom 2: 9m2\n"
        ),
    ),
    PromptTemplate(
        id="rear-extension",
        title="Single storey rear extension",
        description="New extension structure, roof, glazing, underfloor heating, kitchen fit-out, open plan remodel.",
        category="Extensions",
        prompt=(
            "PROPERTY:\n"
            "Type: Semi-detached house\n"
            "Location: London\n"
            "Ceiling height: 2.4m (extension), 2.55m (existing ground floor)\n"
            "Property occupied during works\n"
            "Finish level: high\n"
            "\n"
            "FULL SCOPE:\n"
            "Single storey rear extension with open plan kitchen/diner\n"
            "\n"
            "FLOOR AREAS & ROOMS:\n"
            "Ground Floor\n"
            "  New Extension: 6.0 x 4.0\n"
            "  Existing Kitchen (being opened up): 3.5 x 3.0\n"
            "\n"
            "GROUNDWORKS:\n"
            "Strip topsoil and excavate foundations: 24m2\n"
            "Concrete strip foundations\n"
            "Drainage connections and redirections\n"
            "\n"
            "STRUCTURE:\n"
            "New extension walls — blockwork cavity construction: 32m2\n"
            "Flat roof structure with warm roof insulation: 24m2\n"
            "Knock through existing rear wall to create open plan — 1 no. opening approx 4.5m\n"
            "\n"
            "STEELWORKS:\n"
            "New RSJ beam 254x102 UB @25 with padstones, rear wall opening 4.5m span — specialist subcontract, PC sum £4,200\n"
            "\n"
            "WINDOWS:\n"
            "Bi-fold doors to rear elevation: 4-panel, 3.6m wide (aluminium, contractor supply)\n"
            "Rooflight to flat roof: 1.0 x 2.0m (aluminium, contractor supply)\n"
            "\n"
            "CEILINGS & INSULATION:\n"
            "Insulated plasterboard to extension ceiling: 24m2\n"
            "Floor insulation to extension before screed\n"
            "\n"
            "HEATING:\n"
            "Underfloor heating — wet system to extension: 24m2\n"
            "Manifold connection to existing boiler system\n"
            "\n"
            "PLASTERING:\n"
            "Skim walls and ceiling to new extension: 56m2\n"
            "Patch skim to existing kitchen after structural works: 12m2\n"
            "\n"
            "JOINERY:\n"
            "New kitchen units and island — client supply, contractor fit (3 days carpenter)\n"
            "\n"
            "TILING:\n"
            "Wall tiling to kitchen splashback: 3.6 x 0.6m\n"
            "\n"
            "PLUMBING:\n"
            "New sink and dishwasher connections in kitchen (2 no.)\n"
            "Boiler system extension for UFH\n"
            "\n"
            "ELECTRICAL:\n"
            "Extension: 10 downlights\n"
            "Extension: 8 double sockets\n"
            "Extension: 2 double sockets in island\n"
            "Extension: 1 cooker circuit hardwire\n"
            "\n"
            "DECORATING:\n"
            "Mist coat and 2 coats emulsion to extension walls and ceiling\n"
            "Mist coat and 2 coats emulsion to existing kitchen walls\n"
            "\n"
            "WOODWORK PAINTING:\n"
            "Gloss to skirting boards in extension: 20 lm\n"
            "Gloss to 1 internal door (both sides) and architrave\n"
            "\n"
            "FLOORING:\n"
            "Polished concrete screed to extension: 24m2\n"
            "Engineered timber to existing kitchen: 10.5m2\n"
        ),
    ),
]


def get_prompt_templates() -> list[PromptTemplate]:
    return PROMPT_TEMPLATES
